on: [push]

jobs:
  logsight-init-action:
    runs-on: ubuntu-latest
    name: A job that initializes logsight.ai
    steps:
      - name: Logsight init step
        uses: aiops/logsight-init-action@main
        id: init
        with:
          username: ${{ secrets.LOGSIGHT_USERNAME }}
          password: ${{ secrets.LOGSIGHT_PASSWORD }}
          application_name: ${{ github.ref }}