on: [push]

jobs:
  logsight-init-action:
    runs-on: ubuntu-latest
    name: A job that initializes logsight.ai and log collection.
    steps:
      - name: Logsight init step
        uses: aiops/logsight-init-action@main
        id: logsight-init
        with:
          username: {{ secrets.LOGSIGHT_USERNAME }}
          password: {{ secrets.LOGSIGHT_PASSWORD }}
          application_name: {{ github.ref }}
          tag: {{ github.sha }}